platform :ios, '6.0'

inhibit_all_warnings!

pod 'Nimbus/Photos', :podspec => 'https://gist.github.com/exalted/7655606/raw/ce27220c457984ecd30fb800503b4c299159ace0/Nimbus.podspec'

pod 'SDURLCache', '~> 1.2'
